version: '3'

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mq
    image: "postgres:13.1"
    command: postgres -c 'max_connections=20'
    ports:
      - "5433:5432"
